# Generated by Django 5.0.4 on 2026-04-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('impacts_quota', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'absence_type',
            },
        ),
        migrations.CreateModel(
            name='CareUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'care_unit',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'certification',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_hours_per_week', models.IntegerField()),
                ('leave_days_per_year', models.IntegerField()),
                ('night_shift_allowed', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('criticality_level', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('requires_rest_after', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shift_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='PatientLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patient_count', models.IntegerField()),
                ('occupancy_rate', models.FloatField()),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.careunit')),
            ],
            options={
                'db_table': 'patient_load',
            },
        ),
        migrations.AddField(
            model_name='careunit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_units', to='planning.service'),
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.service')),
            ],
            options={
                'db_table': 'service_status',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('min_staff', models.IntegerField(default=1)),
                ('max_staff', models.IntegerField(default=10)),
                ('care_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='planning.careunit')),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='ShiftRequiredCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.certification')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.shift')),
            ],
            options={
                'db_table': 'shift_required_certification',
                'unique_together': {('shift', 'certification')},
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='required_certifications',
            field=models.ManyToManyField(blank=True, through='planning.ShiftRequiredCertification', to='planning.certification'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.shifttype'),
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.specialty')),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning.shift')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='planning.staff')),
            ],
            options={
                'db_table': 'shift_assignment',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to='planning.staff'),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('souhait', 'Souhait'), ('contrainte', 'Contrainte impérative')], max_length=50)),
                ('description', models.TextField()),
                ('is_hard_constraint', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='planning.staff')),
            ],
            options={
                'db_table': 'preference',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('workload_percent', models.IntegerField(default=100)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.contracttype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='planning.staff')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('is_planned', models.BooleanField(default=True)),
                ('absence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planning.absencetype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='planning.staff')),
            ],
            options={
                'db_table': 'absence',
            },
        ),
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.certification')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='planning.staff')),
            ],
            options={
                'db_table': 'staff_certification',
            },
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_from', to='planning.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.staff')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_to', to='planning.service')),
            ],
            options={
                'db_table': 'staff_loan',
            },
        ),
        migrations.CreateModel(
            name='StaffServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.staff')),
            ],
            options={
                'db_table': 'staff_service_assignment',
            },
        ),
        migrations.CreateModel(
            name='CertificationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='planning.certification')),
                ('required_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='planning.certification')),
            ],
            options={
                'db_table': 'certification_dependency',
                'unique_together': {('parent_cert', 'required_cert')},
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to='planning.staff')),
            ],
            options={
                'db_table': 'staff_role',
                'unique_together': {('staff', 'role')},
            },
        ),
        migrations.CreateModel(
            name='StaffSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.specialty')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_specialties', to='planning.staff')),
            ],
            options={
                'db_table': 'staff_specialty',
                'unique_together': {('staff', 'specialty')},
            },
        ),
    ]
