# Generated by Django 6.0.3 on 2026-04-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('algo_type', models.CharField(choices=[('greedy', 'Algorithme glouton'), ('local_search', 'Recherche locale'), ('simulated_annealing', 'Recuit simulé'), ('genetic', 'Algorithme génétique')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_parameters', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight_consecutive_nights', models.FloatField(default=1.5)),
                ('weight_preferences', models.FloatField(default=1.0)),
                ('weight_workload_balance', models.FloatField(default=2.0)),
                ('weight_service_changes', models.FloatField(default=1.0)),
                ('weight_weekend_equity', models.FloatField(default=0.8)),
                ('weight_adaptation_period', models.FloatField(default=1.2)),
                ('weight_continuity', models.FloatField(default=1.5)),
                ('max_iterations', models.IntegerField(default=100)),
                ('time_limit_seconds', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optimization.optimizationalgorithm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_assignments', models.IntegerField(default=0)),
                ('total_shifts', models.IntegerField(default=0)),
                ('coverage_rate', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optimization.optimizationconfig')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(default=0.0)),
                ('total_shifts_assigned', models.IntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='optimization.optimizationrun')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('run', 'staff')},
            },
        ),
    ]
